<?xml version="1.0"?>
<robot name="wheels" 
       xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="wheel" params="fb lr translateX translateY">
    <link name="wheel_${fb}_${lr}_link">
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" /> 
            <geometry>
                <cylinder length="${wheel_height}" radius="${wheel_radius}" />
            </geometry>
            <material name="Black" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" /> 
            <geometry>
                <cylinder length="${wheel_height}" radius="${wheel_radius}" />
            </geometry>
            <material name="Black" />
        </collision>
        <inertial>
            <mass value="${wheel_mass}" />
            <origin xyz="0 0 0" />
            <cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}" />
        </inertial>
    </link>

    <joint name="wheel_${fb}_${lr}_joint" type="continuous">
        <axis xyz="0 1 0"/>
        <parent link="base_link" />
        <child link="wheel_${fb}_${lr}_link" />
        <origin xyz="${translateX}
                     ${translateY} 
                     0" 
                rpy="0 0 0" />
    </joint>  
  </xacro:macro>

<!-- WHEELS -->

  <wheel fb="back" lr="left"  translateX="${-base_length/2}" translateY="${base_width/2+wheel_radius/2}" />
  <wheel fb="back" lr="right" translateX="${-base_length/2}" translateY="${-base_width/2-wheel_radius/2}" />

</robot>
